name: BedWars
main: BedWars\BedWars
src-namespace-prefix: BedWars
version: 1.1.0
api: 4.0.0

commands:
  bedwars:
    description: "ยง7BedWars Setup Command"
    permission: bedwars.setup
  start:
    description: "ยง6Start BedWars Game"
    permission: bedwars.start
permissions:
  bedwars.setup:
    description: "/bedwars"
    default: true
  bedwars.start:
    description: "/start"
    default: true